export const DATA_AS_OF = '2026-09-01';
export const DATA_VERSION = 'aviation-2026.1';
const col = (name,type,description,references) => ({name,type,description,...(references?{references}: {})});
export const SCHEMA = [
 {name:'PARTS',description:'Master catalog of synthetic aviation part numbers. One row describes a part, not a physical unit.',primaryKey:'PART_NUMBER',columns:[col('PART_NUMBER','TEXT','Unique synthetic catalog number.'),col('DESCRIPTION','TEXT','Aviation component description.'),col('PRODUCT_TYPE','TEXT','LLP: life limited part; REP: repairable; ROT: rotable.'),col('PRODUCT_LINE','TEXT','Engine or aircraft family.'),col('ATA_CHAPTER','INTEGER','ATA system chapter.')]},
 {name:'INVENTORY',description:'Only material physically on hand. Each row is one batch or individually tracked asset.',primaryKey:'BATCH_ID',columns:[col('BATCH_ID','TEXT','Unique stock batch or asset identifier.'),col('PART_NUMBER','TEXT','Catalog part held in stock.','PARTS.PART_NUMBER'),col('CONDITION','TEXT','AR: as removed; SV: serviceable; OH: overhauled.'),col('QTY_ON_HAND','INTEGER','Units physically in the warehouse.'),col('LOCATION','TEXT','Warehouse: ATL, DFW, MIA or LAX.'),col('UNIT_COST','REAL','Acquisition cost per unit in USD, excluding repair cost.'),col('EXT_COST','REAL','Quantity multiplied by acquisition cost per unit.'),col('SOURCE_RO_ID','TEXT','Completed repair that returned this stock, when applicable.','REPAIR_ORDERS.RO_NUMBER'),col('SERIAL_NUMBER','TEXT','Individual asset serial; NULL for batched material.'),col('LIFE_LIMIT_CYCLES','INTEGER','Approved training life limit for an LLP; otherwise NULL.'),col('CYCLES_SINCE_NEW','INTEGER','Cycles accumulated by an LLP; otherwise NULL.'),col('CYCLES_REMAINING','INTEGER','Life limit minus cycles since new; otherwise NULL.')]},
 {name:'SALES',description:'Two years of synthetic sales transactions. Sales are historical, separate from current stock.',primaryKey:'SALE_ID',columns:[col('SALE_ID','TEXT','Unique sale identifier.'),col('SALE_DATE','TEXT','Date sold, YYYY-MM-DD.'),col('CUSTOMER_ID','TEXT','Customer that purchased the material.','CUSTOMERS.CUSTOMER_ID'),col('PART_NUMBER','TEXT','Part sold.','PARTS.PART_NUMBER'),col('QTY_SOLD','INTEGER','Units sold.'),col('UNIT_PRICE','REAL','Selling price per unit in USD.')]},
 {name:'CUSTOMERS',description:'Fictional airline, lessor and material customers.',primaryKey:'CUSTOMER_ID',columns:[col('CUSTOMER_ID','TEXT','Unique customer identifier.'),col('CUSTOMER_NAME','TEXT','Fictional customer name.')]},
 {name:'REPAIR_ORDERS',description:'Material sent to external repair vendors. A NULL return date means the material remains at the vendor.',primaryKey:'RO_NUMBER',columns:[col('RO_NUMBER','TEXT','Unique repair order identifier.'),col('PART_NUMBER','TEXT','Part sent for repair.','PARTS.PART_NUMBER'),col('VENDOR_ID','TEXT','External repair vendor.','VENDORS.VENDOR_ID'),col('DATE_SENT','TEXT','Date shipped to vendor, YYYY-MM-DD.'),col('DATE_RETURNED','TEXT','Date returned; NULL means open.'),col('QTY_SENT','INTEGER','Units sent to vendor.'),col('QTY_SV','INTEGER','Units returned serviceable; NULL until closed.'),col('QTY_SCRAP','INTEGER','Units scrapped; NULL until closed.'),col('REPAIR_COST','REAL','Total invoiced repair cost in USD; NULL until closed. Separate from stock acquisition cost.')]},
 {name:'VENDORS',description:'Fictional external component repair organizations.',primaryKey:'VENDOR_ID',columns:[col('VENDOR_ID','TEXT','Unique vendor identifier.'),col('VENDOR_NAME','TEXT','Fictional external repair organization.')]}
];
const id = (prefix,n,width=4) => prefix+String(n).padStart(width,'0');
const date = days => new Date(Date.UTC(2024,8,2)+days*86400000).toISOString().slice(0,10);
export function createDataset(){
 const d=Object.fromEntries(SCHEMA.map(t=>[t.name,[]]));
 const families=['CFM56','CF6','PW2000','737NG','757','767','A320'];
 const engine=[['LLP','HPC stage 1 disk'],['REP','HPT blade'],['ROT','Fuel control unit'],['LLP','LPT stage 2 disk'],['REP','Combustor liner'],['ROT','Oil scavenge pump']];
 const airframe=[['ROT','Hydraulic pump'],['REP','Main landing gear actuator'],['ROT','Air cycle machine'],['ROT','Generator control unit'],['REP','Flap actuator'],['ROT','Brake control valve']];
 for(let i=0;i<196;i++){const family=families[i%7], [type,description]=(i%7<3?engine:airframe)[Math.floor(i/7)%6];d.PARTS.push({PART_NUMBER:id('FS-'+(i%7+1)+'-',i+1),DESCRIPTION:description+' — '+family+' series '+(1+Math.floor(i/42)),PRODUCT_TYPE:type,PRODUCT_LINE:family,ATA_CHAPTER:i%7<3?72:[29,32,21,24,27,32][Math.floor(i/7)%6]});}
 const names=['Meridian','Atlantic','Pioneer','Summit','Horizon','Northstar','Coastal','Pacific','Frontier','Crescent'];
 for(let i=0;i<40;i++)d.CUSTOMERS.push({CUSTOMER_ID:id('C',i+1),CUSTOMER_NAME:names[i%10]+' '+['Airways','Aviation Leasing','Air Cargo','Material Services'][Math.floor(i/10)]});
 for(let i=0;i<20;i++)d.VENDORS.push({VENDOR_ID:id('V',i+1),VENDOR_NAME:names[i%10]+' '+(i<10?'Component Repair':'Engine Services')});
 for(let i=0;i<700;i++){const p=d.PARTS[(i*17)%196],sent=Math.floor(i*730/700),tat=18+(i%20)*2+(i%9),closed=sent+tat<=729,qty=p.PRODUCT_TYPE==='REP'?4+i%21:1,scrap=closed?(i%7===0?Math.max(1,Math.floor(qty*.3)):0):null;d.REPAIR_ORDERS.push({RO_NUMBER:id('RO',i+1,5),PART_NUMBER:p.PART_NUMBER,VENDOR_ID:d.VENDORS[i%20].VENDOR_ID,DATE_SENT:date(sent),DATE_RETURNED:closed?date(sent+tat):null,QTY_SENT:qty,QTY_SV:closed?qty-scrap:null,QTY_SCRAP:scrap,REPAIR_COST:closed?(qty-scrap)*(700+(i%20)*125)+scrap*100:null});}
 for(let i=0;i<420;i++){const p=d.PARTS[i%196],condition=['AR','SV','OH'][Math.floor(i/4)%3],llp=p.PRODUCT_TYPE==='LLP',qty=p.PRODUCT_TYPE==='REP'?4+i%25:1,cost=llp?45000+(i%29)*2100:p.PRODUCT_TYPE==='ROT'?6200+(i%23)*850:900+(i%31)*110,life=llp?20000:null,used=llp?1000+(i*113)%18000:null;const source=condition==='SV'?d.REPAIR_ORDERS.find(r=>r.PART_NUMBER===p.PART_NUMBER&&r.DATE_RETURNED&&r.QTY_SV>=qty&&!d.INVENTORY.some(b=>b.SOURCE_RO_ID===r.RO_NUMBER)):null;d.INVENTORY.push({BATCH_ID:id('B',i+1,6),PART_NUMBER:p.PART_NUMBER,CONDITION:condition,QTY_ON_HAND:qty,LOCATION:['ATL','DFW','MIA','LAX'][i%4],UNIT_COST:cost,EXT_COST:qty*cost,SOURCE_RO_ID:source?.RO_NUMBER??null,SERIAL_NUMBER:p.PRODUCT_TYPE==='REP'?null:id('SYN-',i+1,6),LIFE_LIMIT_CYCLES:life,CYCLES_SINCE_NEW:used,CYCLES_REMAINING:llp?life-used:null});}
 for(let i=0;i<1600;i++){const p=d.PARTS[(i*13+Math.floor(i/196))%196];d.SALES.push({SALE_ID:id('S',i+1,6),SALE_DATE:date(Math.floor(i*730/1600)),CUSTOMER_ID:d.CUSTOMERS[(i*7)%40].CUSTOMER_ID,PART_NUMBER:p.PART_NUMBER,QTY_SOLD:p.PRODUCT_TYPE==='REP'?2+i%18:1,UNIT_PRICE:p.PRODUCT_TYPE==='LLP'?78000+(i%25)*2000:p.PRODUCT_TYPE==='ROT'?12500+(i%17)*700:2200+(i%13)*175});}
 return d;
}
