import {escapeHtml as esc} from './ui.js';

export function renderLesson(lesson, mission, selectedAnswer) {
 const answered=Number.isInteger(selectedAnswer);
 const correct=selectedAnswer===lesson.check.answerIndex;
 return `<section class="page-heading"><p class="eyebrow">GROUND SCHOOL / BEFORE THE MISSION</p><h1 class="page-title">${esc(lesson.title)}</h1><p class="muted">${esc(lesson.intro)}</p></section>
 <ol class="lesson-flight-plan" aria-label="Learning sequence"><li><span>01</span> Know what you’ll learn</li><li><span>02</span> Learn with Tower</li><li><span>03</span> Apply it in a mission</li></ol>
 <section class="card lesson-outcomes"><p class="eyebrow">YOUR LEARNING OBJECTIVES</p><h2>By the end, you’ll be able to…</h2><ul>${lesson.outcomes.map(item=>`<li>${esc(item)}</li>`).join('')}</ul><p class="form-help">Read at your own pace. These examples are explained practice, not a test. You can reopen this lesson from the mission.</p></section>
 <div class="lesson-sections">${lesson.steps.map((step,i)=>`<section class="card lesson-step"><header><span class="mission-number">${String(i+1).padStart(2,'0')}</span><div><p class="eyebrow">${esc(step.concept)}</p><h2>${esc(step.title)}</h2></div></header><p>${esc(step.body)}</p>${step.sql?`<div class="lesson-example"><p class="eyebrow">WORKED EXAMPLE</p><pre><code>${esc(step.sql)}</code></pre><h3>Read it in plain language</h3><ul>${step.readback.map(line=>`<li>${esc(line)}</li>`).join('')}</ul></div>`:''}<div class="lesson-takeaway"><strong>Remember</strong><p>${esc(step.takeaway)}</p></div></section>`).join('')}</div>
 <section class="card lesson-check"><p class="eyebrow">QUICK READBACK / NO SCORE</p><h2>Check your understanding</h2><p id="lesson-check-question">${esc(lesson.check.question)}</p><div class="lesson-options" role="group" aria-labelledby="lesson-check-question">${lesson.check.options.map((option,i)=>`<button class="lesson-option ${selectedAnswer===i?'selected':''}" data-action="lesson-answer" data-answer="${i}" aria-pressed="${selectedAnswer===i}"><span>${String.fromCharCode(65+i)}</span>${esc(option)}</button>`).join('')}</div>${answered?`<div class="tower-card" role="status"><p class="eyebrow">TOWER / ${correct?'GOOD READBACK':'LET’S WALK THROUGH IT'}</p><p>${esc(lesson.check.explanation)}</p>${!correct?'<p class="form-help">You can try another answer or reread the example. This does not affect your mission record.</p>':''}</div>`:''}</section>
 <section class="campaign-card lesson-apply"><div><p class="eyebrow">NOW APPLY WHAT YOU’VE LEARNED</p><h2>${esc(mission.title)}</h2><p>${esc(lesson.apply)}</p></div><button class="button primary" data-action="begin-mission">Apply it in the mission →</button></section>`;
}
